# Generated by Django 2.0.4 on 2018-04-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя артиста')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('genre', models.SmallIntegerField(choices=[(0, 'Pop'), (1, 'R&B')], null=True, verbose_name='Жанр')),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Адрес аватарки')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
            },
        ),
    ]
