# Generated by Django 2.0.4 on 2018-04-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180417_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumsong',
            options={'verbose_name': 'Альбом/Песня', 'verbose_name_plural': 'Альбомы/Песни'},
        ),
    ]
