# Generated by Django 2.0.4 on 2018-04-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180418_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.SmallIntegerField(choices=[(0, 'Pop'), (1, 'R&B'), (2, 'Rap'), (3, 'Alternative'), (4, 'Hip Hop')], null=True, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=2500, verbose_name='Содержание'),
        ),
    ]
